In [1]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [ ]:
a  = np.array([[i for i in range(1, 10)],[i for i in range(1, 10)],[i for i in range(1, 10)]])

In [7]:
a

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [13]:
b = np.arange(1,10,3)

In [14]:
b

array([1, 4, 7])

In [19]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [20]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
np.random.rand(1,10)

array([[0.97906907, 0.11411784, 0.6542576 , 0.61195827, 0.36521148,
        0.87704285, 0.93138719, 0.15499524, 0.74177525, 0.02515924]])